-- autogenerated lush spec on Thu 23 Nov 2023 12:40:21 AM CST
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv

local latte = {
  rosewater = "#dc8a78",
  flamingo = "#dd7878",
  pink = "#ea76cb",
  mauve = "#8839ef",
  red = "#d20f39",
  maroon = "#e64553",
  peach = "#fe640b",
  yellow = "#df8e1d",
  green = "#40a02b",
  teal = "#179299",
  sky = "#04a5e5",
  saphire = "#209fb5",
  blue = "#1e66f5",
  lavender = "#7287fd",
  -- text = "#4c4f69",
  -- subtext1 = "#5c5f77",
  -- subtext0 = "#6c6f85",
  -- overlay2 = "#7c7f93",
  -- overlay1 = "#8c8fa1",
  -- overlay0 = "#9ca0b0",
  -- surface2 = "#acb0be",
  -- surface1 = "#bcc0cc",
  -- surface0 = "#ccd0da",
  -- base = "#eff1f5",
  -- mantle = "#e6e9ef",
  -- crust = "#dce0e8",
}

local mocha = {
  rosewater = hsl("#f5e0dc"),
  flamingo = hsl("#f2cdcd"),
  pink = hsl("#f5c2e7"),
  mauve = hsl("#cba6f7"),
  red = hsl("#f37ba8"),
  maroon = hsl("#eba0ac"),
  peach = hsl("#fab387"),
  yellow = hsl("#f9e2af"),
  green = hsl("#abe9b3"),
  teal = hsl("#94e2d5"),
  sky = hsl("#89dceb"),
  saphire = hsl("#74c7ec"),
  blue = hsl("#89b4fa"),
  lavender = hsl("#b4befe"),
  text = hsl("#cdd6f4"),
  subtext1 = hsl("#bac2de"),
  subtext0 = hsl("#a6adc8"),
  overlay2 = hsl("#9399b2"),
  overlay1 = hsl("#7f849c"),
  overlay0 = hsl("#6c7086"),
  surface2 = hsl("#585b70"),
  surface1 = hsl("#45475a"),
  surface0 = hsl("#313244"),
  base = hsl("#1e1e2e"),
  mantle = hsl("#181825"),
  crust = hsl("#11111b"),
}

local custom = {
  black = hsl("#0f0f17"),
  text = hsl("#cdd6f4"),
  -- black = catppuccin_mocha.base.darken(50),
  verdant_green = hsl("#37a3a5"),

  red = hsl("#E95678"),
  baby_pink = hsl("#f86587"),
  pink = hsl("#ff7eb6"),
  horizon_orange = hsl("#F09383"),
  orange = hsl("#ff9e64"),
  yellow = hsl("#f6ca6b"),
  tokyodark_green = hsl("#95c561"),
  pale_yellow_green = hsl("#e5fcc2"),
  yellow_green = hsl("#BAE881"),
  pale_green = hsl("#c7f9cc"),
  dead_green = hsl("#9de0ad"),
  green = hsl("#80ed99"),
  green1 = hsl("#42be65"),
  vibrant_green = hsl("#2EE6A6"),
  teal = hsl("#1abc9c"),
  green_cyan = hsl("#25B2BC"),
  cyan = hsl("#18B8D9"),
  pale_blue = hsl("#A4C8DE"),
  light_blue = hsl("#7dcfff"),
  blue = hsl("#78a9ff"),
  nord_blue = hsl("#6b9cf2"),
  purple = hsl("#be95ff"),
  dark_purple = hsl("#9d7cd8"),
}


-- LSP/Linters mistakenly show `undefined global` errors in the spec, they may
-- support an annotation like the following. Consult your server documentation.
---@diagnostic disable: undefined-global
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {

    TabLine = { bg = mocha.mantle, fg = mocha.surface1 },
    TabLineFill = { bg = mocha.mantle, fg = mocha.surface1 },

    ColorColumn    { bg = mocha.surface0 }, -- Columns set with 'colorcolumn'
    Conceal        { fg = mocha.overlay1 }, -- Placeholder characters substituted for concealed text (see 'conceallevel')
    Cursor         { fg = custom.black, bg = mocha.text }, -- Character under the cursor (NOTE: get overwritten by terminal config)
    CurSearch      { bg = custom.red, fg = custom.black }, -- Highlighting a search pattern under the cursor (see 'hlsearch')
    lCursor        { fg = custom.black, bg = mocha.text}, -- Character under the cursor when |language-mapping| is used (see 'guicursor')
    CursorIM       {  fg="#0f0f17", bg="#cdd6f4", }, -- Like Cursor, but used when in IME mode |CursorIM|
    CursorColumn   { bg="#282737",  }, -- Screen-column at the cursor, when 'cursorcolumn' is set.
    CursorLine     { }, -- Screen-line at the cursor, when 'cursorline' is set. Low-priority if foreground (ctermfg OR guifg) is not set.
    Directory      {  fg = custom.verdant_green, }, -- Directory names (and other special names in listings)
    DiffAdd        {  bg="#2b3633", }, -- Diff mode: Added line |diff.txt|
    DiffChange     {  bg="#161a27", }, -- Diff mode: Changed line |diff.txt|
    DiffDelete     {  bg="#361c28", }, -- Diff mode: Deleted line |diff.txt|
    DiffText       {  bg="#222b41", }, -- Diff mode: Changed text within a changed line |diff.txt|
    EndOfBuffer    {  fg="#0f0f17", }, -- Filler lines (~) after the end of the buffer. By default, this is highlighted like |hl-NonText|.
    TermCursor     {  gui="reverse", }, -- Cursor in a focused terminal
    TermCursorNC   { }, -- Cursor in an unfocused terminal
    ErrorMsg       { fg = custom.red, bg = custom.black, gui = "bold" }, -- Error messages on the command line
    VertSplit      {  fg= mocha.surface0, }, -- Column separating vertically split windows
    Winseparator   { fg = mocha.surface0,  }, -- Separator between window splits. Inherts from |hl-VertSplit| by default, which it will replace eventually.
    Folded         {  fg="#cdd6f4", bg="#282737", }, -- Line used for closed folds
    FoldColumn     {  fg="#7dcfff", bg="#282737", }, -- 'foldcolumn'
    SignColumn     {  fg= mocha.surface0, }, -- Column where |signs| are displayed
    Search         { fg= mocha.surface0, bg= custom.pink, }, -- Last search pattern highlighting (see 'hlsearch'). Also used for similar items that need to stand out.
    IncSearch      { fg="#282737", bg="#f6ca6b", }, -- 'incsearch' highlighting; also used for the text replaced with ":s///c"
    -- Substitute     { bg = base00, fg = base01 }, -- |:substitute| replacement text highlighting
    LineNr         { fg = mocha.surface1, gui="italic" }, -- Line number for ":number" and ":#" commands, and when 'number' or 'relativenumber' option is set.
    LineNrAbove    { LineNr }, -- Line number for when the 'relativenumber' option is set, above the cursor line
    LineNrBelow    { LineNr }, -- Line number for when the 'relativenumber' option is set, below the cursor line
    CursorLineNr   { fg = custom.green }, -- Like LineNr when 'cursorline' or 'relativenumber' is set for the cursor line.
    CursorLineFold { FoldColumn }, -- Like FoldColumn when 'cursorline' is set for the cursor line
    CursorLineSign {  SignColumn }, -- Like SignColumn when 'cursorline' is set for the cursor line
    MatchParen     { fg= custom.verdant_green, gui="bold", bg=custom.black.lighten(10) }, -- Character under the cursor or just before it, if it is a paired bracket, and its match. |pi_paren.txt|
    ModeMsg        {  fg="#80ed99", gui="bold", }, -- 'showmode' message (e.g., "-- INSERT -- ")
    -- MsgArea        { }, -- Area for messages and cmdline
    -- MsgSeparator   { }, -- Separator for scrolled messages, `msgsep` flag of 'display'
    MoreMsg        { fg="#80ed99", }, -- |more-prompt|
    NonText        { fg="#383747",  }, -- '@' at the end of the window, characters from 'showbreak' and other characters that do not really exist in the text (e.g., ">" displayed when a double-wide character doesn't fit at the end of the line). See also |hl-EndOfBuffer|.
    Normal         { fg="#cdd6f4", bg="#0f0f17", }, -- Normal text
    NormalFloat    { Normal }, -- Normal text in floating windows.

    Whitespace     { fg= mocha.surface0, }, -- "nbsp", "space", "tab" and "trail" in 'listchars'


    SpecialKey                                  { fg="#383747", }, -- SpecialKey     xxx guifg=#383747
    NvimTreeEndOfBuffer                         { EndOfBuffer }, -- NvimTreeEndOfBuffer xxx links to EndOfBuffer
    IblWhitespace                               { NonText }, -- IblWhitespace  xxx links to NonText
    NvimTreeSymlinkFolderName                   { Directory }, -- NvimTreeSymlinkFolderName xxx links to Directory
    NvimInvalidSpacing                          { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    HopPreview                                  { IncSearch }, -- HopPreview     xxx links to IncSearch
    Comment                                     { fg= mocha.overlay0 },
    -- CursorLine     { bg = custom.black.lighten(16) }, -- Screen-line at the cursor, when 'cursorline' is set. Low-priority if foreground (ctermfg OR guifg) is not set.
    MarkSignNumHL                               { CursorLineNr }, -- MarkSignNumHL  xxx links to CursorLineNr
    NvimTreeCursorLineNr                        { CursorLineNr }, -- NvimTreeCursorLineNr xxx links to CursorLineNr
    Question                                    { fg = custom.verdant_green, }, -- Question       xxx guifg=#38a3a5
    StatusLine                                  { fg="#cdd6f4", bg="#181825", }, -- StatusLine     xxx guifg=#cdd6f4 guibg=#181825
    NvimTreeStatusLine                          { StatusLine }, -- NvimTreeStatusLine xxx links to StatusLine
    StatusLineNC                                { fg="#45475a", bg="#181825", }, -- StatusLineNC   xxx guifg=#45475a guibg=#181825
    Title                                       { fg = custom.verdant_green, gui="bold", }, -- Title          xxx cterm=bold gui=bold guifg=#38a3a5
    FloatTitle                                  { Title }, -- FloatTitle     xxx links to Title
    Visual                                      { gui="bold", bg="#2f2e3e", }, -- Visual         xxx cterm=bold gui=bold guibg=#2f2e3e
    WarningMsg                                  { fg="#78a9ff", }, -- WarningMsg     xxx guifg=#78a9ff
    WildMenu                                    { fg="#78a9ff", bg="#ff7eb6", }, -- WildMenu       xxx guifg=#78a9ff guibg=#ff7eb6
    GitSignsAddPreview                          { DiffAdd }, -- GitSignsAddPreview xxx links to DiffAdd
    GitSignsDeletePreview                       { DiffDelete }, -- GitSignsDeletePreview xxx links to DiffDelete
    SpellBad                                    { sp="#78a9ff", gui="undercurl", }, -- SpellBad       xxx cterm=undercurl gui=undercurl guisp=#78a9ff
    NvimTreeCutHL                               { SpellBad }, -- NvimTreeCutHL  xxx links to SpellBad
    SpellCap                                    { sp = custom.verdant_green, gui="undercurl", }, -- SpellCap       xxx cterm=undercurl gui=undercurl guisp=#38a3a5
    SpellRare                                   { sp="#be95ff", gui="undercurl", }, -- SpellRare      xxx cterm=undercurl gui=undercurl guisp=#be95ff
    NvimTreeCopiedHL                            { SpellRare }, -- NvimTreeCopiedHL xxx links to SpellRare
    SpellLocal                                  { sp="#7dcfff", gui="undercurl", }, -- SpellLocal     xxx cterm=undercurl gui=undercurl guisp=#7dcfff
    NvimTreeBookmarkHL                          { SpellLocal }, -- NvimTreeBookmarkHL xxx links to SpellLocal
    Pmenu                                       { fg="#cdd6f4", bg="#27272e", }, -- Pmenu          xxx guifg=#cdd6f4 guibg=#27272e
    PmenuKind                                   { Pmenu }, -- PmenuKind      xxx links to Pmenu
    PmenuExtra                                  { Pmenu }, -- PmenuExtra     xxx links to Pmenu
    PmenuSel                                    { fg="#0f0f17", gui="bold", bg = custom.verdant_green, }, -- PmenuSel       xxx cterm=bold gui=bold guifg=#0f0f17 guibg=#38a3a5
    PmenuKindSel                                { PmenuSel }, -- PmenuKindSel   xxx links to PmenuSel
    PmenuExtraSel                               { PmenuSel }, -- PmenuExtraSel  xxx links to PmenuSel
    PmenuSbar                                   { bg="#27272e", }, -- PmenuSbar      xxx guibg=#27272e
    PmenuThumb                                  { bg="#d7def6", }, -- PmenuThumb     xxx guibg=#d7def6
    TabLine                                     { fg="#45475a", bg="#181825", }, -- TabLine        xxx guifg=#45475a guibg=#181825
    HarpoonInactive                             { TabLine }, -- HarpoonInactive xxx links to TabLine
    HarpoonNumberInactive                       { TabLine }, -- HarpoonNumberInactive xxx links to TabLine
    TabLineSel                                  { fg="#abe9b3", bg="#45475a", }, -- TabLineSel     xxx guifg=#abe9b3 guibg=#45475a
    TabLineFill                                 {}, -- TabLineSel     xxx guifg=#abe9b3 guibg=#45475a
    HarpoonActive                               { TabLineSel }, -- HarpoonActive  xxx links to TabLineSel
    HarpoonNumberActive                         { TabLineSel }, -- HarpoonNumberActive xxx links to TabLineSel
    NvimTreeCursorColumn                        { CursorColumn }, -- NvimTreeCursorColumn xxx links to CursorColumn
    QuickFixLine                                { gui="bold", bg="#282737", }, -- QuickFixLine   xxx cterm=bold gui=bold guibg=#282737
    NormalNC                                    { fg="#cdd6f4", bg="#0f0f17", }, -- NormalNC       xxx guifg=#cdd6f4 guibg=#0f0f17
    NormalFloat                                 { fg="#cdd6f4", bg="#0d0c14", }, -- NormalFloat    xxx guifg=#cdd6f4 guibg=#0d0c14
    NvimTreeNormalFloat                         { NormalFloat }, -- NvimTreeNormalFloat xxx links to NormalFloat
    FloatBorder                                 { fg="#78a9ff", }, -- FloatBorder    xxx guifg=#78a9ff
    TelescopeBorder                             { FloatBorder }, -- TelescopeBorder xxx links to FloatBorder
    WinBar                                      { fg= mocha.rosewater, }, -- WinBar         xxx guifg=#f5e0dc
    WinBarNC                                    { WinBar }, -- WinBarNC       xxx links to WinBar
    HopCursor                                   { Cursor }, -- HopCursor      xxx links to Cursor
    NvimSpacing                                 { Normal }, -- NvimSpacing    xxx links to Normal
    NvimTreePopup                               { Normal }, -- NvimTreePopup  xxx links to Normal
    markdownError                               { Normal }, -- markdownError  xxx links to Normal
    Substitute                                  { fg="#282737", bg="#ff7eb6", }, -- Substitute     xxx guifg=#282737 guibg=#ff7eb6
    FloatShadow                                 { bg="black", blend=80, }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                          { bg="black", blend=100, }, -- FloatShadowThrough xxx guibg=Black blend=100
    RedrawDebugNormal                           { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                            { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                         { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                        { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                       { fg="#0f0f17", bg="#e95678", }, -- Error          xxx guifg=#0f0f17 guibg=#e95678
    NvimInvalid                                 { Error }, -- NvimInvalid    xxx links to Error
    luaParenError                               { Error }, -- luaParenError  xxx links to Error
    luaError                                    { Error }, -- luaError       xxx links to Error
    Todo                                        { fg="#ff7eb6", gui="bold", bg="#282737", }, -- Todo           xxx cterm=bold gui=bold guifg=#ff7eb6 guibg=#282737
    luaTodo                                     { Todo }, -- luaTodo        xxx links to Todo
    String                                      { fg="#80ed99", }, -- String         xxx guifg=#80ed99
    sym"@string"                                { String }, -- @string        xxx links to String
    NvimString                                  { String }, -- NvimString     xxx links to String
    luaString2                                  { String }, -- luaString2     xxx links to String
    luaString                                   { String }, -- luaString      xxx links to String
    Constant                                    { fg="#78a9ff", }, -- Constant       xxx guifg=#78a9ff
    sym"@lsp.type.enumMember"                   { Constant }, -- @lsp.type.enumMember xxx links to Constant
    luaConstant                                 { Constant }, -- luaConstant    xxx links to Constant
    Character                                   { fg="#78a9ff", }, -- Character      xxx guifg=#78a9ff
    Number                                      { fg="#f6ca6b", }, -- Number         xxx guifg=#f6ca6b
    sym"@number"                                { Number }, -- @number        xxx links to Number
    NvimNumber                                  { Number }, -- NvimNumber     xxx links to Number
    luaNumber                                   { Number }, -- luaNumber      xxx links to Number
    Boolean                                     { fg="#f6ca6b", gui="bold", }, -- Boolean        xxx cterm=bold gui=bold guifg=#f6ca6b
    sym"@boolean"                               { Boolean }, -- @boolean       xxx links to Boolean
    Float                                       { fg="#f6ca6b", }, -- Float          xxx guifg=#f6ca6b
    Function                                    { fg = custom.verdant_green, gui="bold", }, -- Function       xxx cterm=bold gui=bold guifg=#38a3a5
    sym"@lsp.type.decorator"                    { Function }, -- @lsp.type.decorator xxx links to Function
    sym"@lsp.type.function"                     { Function }, -- @lsp.type.function xxx links to Function
    sym"@lsp.type.method"                       { Function }, -- @lsp.type.method xxx links to Function
    sym"@method.call.php"                       { Function }, -- @method.call.php xxx links to Function
    sym"@method.php"                            { Function }, -- @method.php    xxx links to Function
    luaMetaMethod                               { Function }, -- luaMetaMethod  xxx links to Function
    luaFunction                                 { Function }, -- luaFunction    xxx links to Function
    Identifier                                  { fg="#78a9ff", }, -- Identifier     xxx guifg=#78a9ff
    NvimIdentifier                              { Identifier }, -- NvimIdentifier xxx links to Identifier
    MarkSignHL                                  { Identifier }, -- MarkSignHL     xxx links to Identifier
    luaFunc                                     { Identifier }, -- luaFunc        xxx links to Identifier
    Conditional                                 { fg="#be95ff", gui="bold", }, -- Conditional    xxx cterm=bold gui=bold guifg=#be95ff
    sym"@conditional"                           { Conditional }, -- @conditional   xxx links to Conditional
    luaCondElse                                 { Conditional }, -- luaCondElse    xxx links to Conditional
    luaCond                                     { Conditional }, -- luaCond        xxx links to Conditional
    Statement                                   { fg="#78a9ff", }, -- Statement      xxx guifg=#78a9ff
    luaStatement                                { Statement }, -- luaStatement   xxx links to Statement
    Repeat                                      { fg="#ff7eb6", gui="bold", }, -- Repeat         xxx cterm=bold gui=bold guifg=#ff7eb6
    sym"@repeat"                                { Repeat }, -- @repeat        xxx links to Repeat
    luaRepeat                                   { Repeat }, -- luaRepeat      xxx links to Repeat
    luaFor                                      { Repeat }, -- luaFor         xxx links to Repeat
    Label                                       { fg="#ff7eb6", }, -- Label          xxx guifg=#ff7eb6
    sym"@label"                                 { Label }, -- @label         xxx links to Label
    luaLabel                                    { Label }, -- luaLabel       xxx links to Label
    Operator                                    { fg="#be95ff", gui="bold", }, -- Operator       xxx cterm=bold gui=bold guifg=#be95ff
    sym"@operator"                              { Operator }, -- @operator      xxx links to Operator
    NvimAssignment                              { Operator }, -- NvimAssignment xxx links to Operator
    NvimOperator                                { Operator }, -- NvimOperator   xxx links to Operator
    luaOperator                                 { Operator }, -- luaOperator    xxx links to Operator
    Keyword                                     { fg="#be95ff", gui="italic", }, -- Keyword        xxx cterm=italic gui=italic guifg=#be95ff
    sym"@type.qualifier.php"                    { Keyword }, -- @type.qualifier.php xxx links to Keyword
    Exception                                   { fg="#78a9ff", }, -- Exception      xxx guifg=#78a9ff
    Include                                     { fg = custom.verdant_green, gui="italic", }, -- Include        xxx cterm=italic gui=italic guifg=#38a3a5
    sym"@include"                               { Include }, -- @include       xxx links to Include
    PreProc                                     { fg="#ff7eb6", }, -- PreProc        xxx guifg=#ff7eb6
    PreCondit                                   { PreProc }, -- PreCondit      xxx links to PreProc
    sym"@preproc"                               { PreProc }, -- @preproc       xxx links to PreProc
    Define                                      { fg="#be95ff", }, -- Define         xxx guifg=#be95ff
    sym"@define"                                { Define }, -- @define        xxx links to Define
    Macro                                       { fg="#78a9ff", }, -- Macro          xxx guifg=#78a9ff
    sym"@macro"                                 { Macro }, -- @macro         xxx links to Macro
    sym"@lsp.type.macro"                        { Macro }, -- @lsp.type.macro xxx links to Macro
    StorageClass                                { fg="#ff7eb6", }, -- StorageClass   xxx guifg=#ff7eb6
    sym"@storageclass"                          { StorageClass }, -- @storageclass  xxx links to StorageClass
    Type                                        { fg="#ff7eb6", }, -- Type           xxx guifg=#ff7eb6
    sym"@type"                                  { Type }, -- @type          xxx links to Type
    sym"@lsp.type.type"                         { Type }, -- @lsp.type.type xxx links to Type
    NvimNumberPrefix                            { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                             { Type }, -- NvimOptionSigil xxx links to Type
    Structure                                   { fg="#be95ff", }, -- Structure      xxx guifg=#be95ff
    sym"@lsp.type.class"                        { Structure }, -- @lsp.type.class xxx links to Structure
    sym"@lsp.type.struct"                       { Structure }, -- @lsp.type.struct xxx links to Structure
    luaTable                                    { Structure }, -- luaTable       xxx links to Structure
    Typedef                                     { fg="#ff7eb6", }, -- Typedef        xxx guifg=#ff7eb6
    sym"@lsp.type.typeParameter"                { Typedef }, -- @lsp.type.typeParameter xxx links to Typedef
    Tag                                         { fg="#ff7eb6", }, -- Tag            xxx guifg=#ff7eb6
    Special                                     { fg="#7dcfff", }, -- Special        xxx guifg=#7dcfff
    SpecialComment                              { Special }, -- SpecialComment xxx links to Special
    SpecialChar                                 { fg="#93baff", }, -- SpecialChar    xxx guifg=#93baff
    sym"@character.special"                     { SpecialChar }, -- @character.special xxx links to SpecialChar
    NvimRegister                                { SpecialChar }, -- NvimRegister   xxx links to SpecialChar
    NvimStringSpecial                           { SpecialChar }, -- NvimStringSpecial xxx links to SpecialChar
    luaSpecial                                  { SpecialChar }, -- luaSpecial     xxx links to SpecialChar
    Delimiter                                   { fg="#93baff", }, -- Delimiter      xxx guifg=#93baff
    sym"@punctuation"                           { Delimiter }, -- @punctuation   xxx links to Delimiter
    NvimParenthesis                             { Delimiter }, -- NvimParenthesis xxx links to Delimiter
    NvimColon                                   { Delimiter }, -- NvimColon      xxx links to Delimiter
    NvimComma                                   { Delimiter }, -- NvimComma      xxx links to Delimiter
    NvimArrow                                   { Delimiter }, -- NvimArrow      xxx links to Delimiter
    Debug                                       { fg="#78a9ff", }, -- Debug          xxx guifg=#78a9ff
    sym"@debug"                                 { Debug }, -- @debug         xxx links to Debug
    DiagnosticError                             { fg="#e95678", gui="italic", }, -- DiagnosticError xxx cterm=italic gui=italic guifg=#e95678
    NvimTreeLspDiagnosticsError                 { DiagnosticError }, -- NvimTreeLspDiagnosticsError xxx links to DiagnosticError
    DiagnosticWarn                              { fg="#fae3b0", gui="italic", }, -- DiagnosticWarn xxx cterm=italic gui=italic guifg=#fae3b0
    NvimTreeLspDiagnosticsWarning               { DiagnosticWarn }, -- NvimTreeLspDiagnosticsWarning xxx links to DiagnosticWarn
    DiagnosticInfo                              { fg="#89dceb", gui="italic", }, -- DiagnosticInfo xxx cterm=italic gui=italic guifg=#89dceb
    NvimTreeLspDiagnosticsInformation           { DiagnosticInfo }, -- NvimTreeLspDiagnosticsInformation xxx links to DiagnosticInfo
    DiagnosticHint                              { fg="#be95ff", gui="italic", }, -- DiagnosticHint xxx cterm=italic gui=italic guifg=#be95ff
    NvimTreeLspDiagnosticsHint                  { DiagnosticHint }, -- NvimTreeLspDiagnosticsHint xxx links to DiagnosticHint
    DiagnosticOk                                { fg="lightgreen", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticVirtualTextOk                     { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticFloatingOk                        { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticSignOk                            { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    DiagnosticUnderlineError                    { sp="#e95678", gui="underline", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=#e95678
    DiagnosticUnderlineWarn                     { sp="#fae3b0", gui="underline", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=#fae3b0
    DiagnosticUnderlineInfo                     { sp="#89dceb", gui="underline", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=#89dceb
    DiagnosticUnderlineHint                     { sp="#b5e8e0", gui="underline", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=#b5e8e0
    DiagnosticUnderlineOk                       { sp="lightgreen", gui="underline", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    DiagnosticVirtualTextError                  { fg="#e95678", gui="italic", bg="#241620", }, -- DiagnosticVirtualTextError xxx cterm=italic gui=italic guifg=#e95678 guibg=#241620
    DiagnosticVirtualTextWarn                   { fg="#fae3b0", gui="italic", bg="#252326", }, -- DiagnosticVirtualTextWarn xxx cterm=italic gui=italic guifg=#fae3b0 guibg=#252326
    DiagnosticVirtualTextInfo                   { fg="#89dceb", gui="italic", bg="#1b222b", }, -- DiagnosticVirtualTextInfo xxx cterm=italic gui=italic guifg=#89dceb guibg=#1b222b
    DiagnosticVirtualTextHint                   { fg="#b5e8e0", gui="italic", bg="#1f242a", }, -- DiagnosticVirtualTextHint xxx cterm=italic gui=italic guifg=#b5e8e0 guibg=#1f242a
    DiagnosticFloatingError                     { fg="#e95678", }, -- DiagnosticFloatingError xxx guifg=#e95678
    DiagnosticFloatingWarn                      { fg="#fae3b0", }, -- DiagnosticFloatingWarn xxx guifg=#fae3b0
    DiagnosticFloatingInfo                      { fg="#89dceb", }, -- DiagnosticFloatingInfo xxx guifg=#89dceb
    DiagnosticFloatingHint                      { fg="#b5e8e0", }, -- DiagnosticFloatingHint xxx guifg=#b5e8e0
    DiagnosticSignError                         { fg="#e95678", }, -- DiagnosticSignError xxx guifg=#e95678
    DiagnosticSignWarn                          { fg="#fae3b0", }, -- DiagnosticSignWarn xxx guifg=#fae3b0
    DiagnosticSignInfo                          { fg="#89dceb", }, -- DiagnosticSignInfo xxx guifg=#89dceb
    DiagnosticSignHint                          { fg="#b5e8e0", }, -- DiagnosticSignHint xxx guifg=#b5e8e0
    DiagnosticDeprecated                        { sp="red", gui="strikethrough", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    DiagnosticUnnecessary                       { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@comment"                               { Comment }, -- @comment       xxx links to Comment
    MarkVirtTextHL                              { Comment }, -- MarkVirtTextHL xxx links to Comment
    luaComment                                  { Comment }, -- luaComment     xxx links to Comment
    sym"@text"                                  { fg="#cdd6f4", }, -- @text          xxx guifg=#cdd6f4
    sym"@text.literal"                          { fg="#f6ca6b", }, -- @text.literal  xxx guifg=#f6ca6b
    sym"@text.reference"                        { gui="bold", }, -- @text.reference xxx cterm=bold gui=bold
    sym"@text.title"                            { fg="#78a9ff", gui="bold", }, -- @text.title    xxx cterm=bold gui=bold guifg=#78a9ff
    sym"@text.uri"                              { fg="#f6ca6b", gui="underline,italic", }, -- @text.uri      xxx cterm=underline,italic gui=underline,italic guifg=#f6ca6b
    Underlined                                  { fg="#80ed99", }, -- Underlined     xxx guifg=#80ed99
    sym"@text.todo"                             { fg="#0f0f17", bg="#fae3b0", }, -- @text.todo     xxx guifg=#0f0f17 guibg=#fae3b0
    sym"@constant"                              { fg="#ff9d64", }, -- @constant      xxx guifg=#ff9d64
    sym"@constant.builtin"                      { fg="#f6ca6b", gui="italic", }, -- @constant.builtin xxx cterm=italic gui=italic guifg=#f6ca6b
    sym"@constant.macro"                        { fg="#78a9ff", }, -- @constant.macro xxx guifg=#78a9ff
    sym"@string.escape"                         { fg="#7dcfff", }, -- @string.escape xxx guifg=#7dcfff
    sym"@string.special"                        { fg="#78a9ff", }, -- @string.special xxx guifg=#78a9ff
    sym"@character"                             { fg="#78a9ff", }, -- @character     xxx guifg=#78a9ff
    sym"@float"                                 { fg="#f6ca6b", }, -- @float         xxx guifg=#f6ca6b
    sym"@function"                              { fg = custom.verdant_green, }, -- @function      xxx guifg=#38a3a5
    sym"@function.call"                         { sym"@function" }, -- @function.call xxx links to @function
    sym"@function.builtin"                      { fg = custom.verdant_green, gui="bold,italic", }, -- @function.builtin xxx cterm=bold,italic gui=bold,italic guifg=#38a3a5
    sym"@lsp.typemod.method.defaultLibrary"     { sym"@function.builtin" }, -- @lsp.typemod.method.defaultLibrary xxx links to @function.builtin
    sym"@lsp.typemod.function.defaultLibrary"   { sym"@function.builtin" }, -- @lsp.typemod.function.defaultLibrary xxx links to @function.builtin
    sym"@function.macro"                        { fg="#78a9ff", gui="bold,italic", }, -- @function.macro xxx cterm=bold,italic gui=bold,italic guifg=#78a9ff
    sym"@parameter"                             { fg="#78a9ff", gui="italic", }, -- @parameter     xxx cterm=italic gui=italic guifg=#78a9ff
    sym"@lsp.type.parameter"                    { sym"@parameter" }, -- @lsp.type.parameter xxx links to @parameter
    sym"@method"                                { fg = custom.verdant_green, gui="bold,italic", }, -- @method        xxx cterm=bold,italic gui=bold,italic guifg=#38a3a5
    sym"@method.call"                           { sym"@method" }, -- @method.call   xxx links to @method
    sym"@field"                                 { fg="#78a9ff", }, -- @field         xxx guifg=#78a9ff
    sym"@property"                              { fg="#78a9ff", gui="italic", }, -- @property      xxx cterm=italic gui=italic guifg=#78a9ff
    sym"@lsp.type.property"                     { sym"@property" }, -- @lsp.type.property xxx links to @property
    sym"@constructor"                           { fg="#7dcfff", }, -- @constructor   xxx guifg=#7dcfff
    sym"@keyword"                               { fg="#be95ff", }, -- @keyword       xxx guifg=#be95ff
    sym"@lsp.type.keyword"                      { sym"@keyword" }, -- @lsp.type.keyword xxx links to @keyword
    sym"@exception"                             { fg="#78a9ff", gui="italic", }, -- @exception     xxx cterm=italic gui=italic guifg=#78a9ff
    sym"@variable"                              { fg="#cdd6f4", }, -- @variable      xxx guifg=#cdd6f4
    sym"@lsp.typemod.variable.injected"         { sym"@variable" }, -- @lsp.typemod.variable.injected xxx links to @variable
    sym"@namespace"                             { fg="#78a9ff", gui="italic", }, -- @namespace     xxx cterm=italic gui=italic guifg=#78a9ff
    sym"@lsp.type.namespace"                    { sym"@namespace" }, -- @lsp.type.namespace xxx links to @namespace
    sym"@tag"                                   { fg="#9d7dd8", }, -- @tag           xxx guifg=#9d7dd8
    Ignore                                      { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                           { fg="#e95678", }, -- NvimInternalError xxx guifg=#e95678
    NvimFigureBrace                             { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape               { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape        { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError

    HopNextKey                                  { fg= custom.verdant_green, gui="bold", }, -- HopNextKey     xxx cterm=bold gui=bold guifg=#ff9d64
    HopNextKey1                                 { fg= custom.green, gui="bold", }, -- HopNextKey1    xxx cterm=bold gui=bold guifg=#78a9ff
    HopNextKey2                                 { fg= mocha.surface2, gui="bold,italic", }, -- HopNextKey2    xxx cterm=bold,italic gui=bold,italic guifg=#b5e8e0
    HopUnmatched                                { fg= mocha.surface0, }, -- HopUnmatched   xxx guifg=#6c7086
    -- HopUnmatched                                { fg="#6c7086", }, -- HopUnmatched   xxx guifg=#6c7086

    -- LspInfoFiletype                             { }, -- LspInfoFiletype xxx cterm= gui=
    -- LspInfoTitle                                { }, -- LspInfoTitle   xxx cterm= gui=
    -- LspInfoTip                                  { }, -- LspInfoTip     xxx cterm= gui=
    -- LspInfoList                                 { }, -- LspInfoList    xxx cterm= gui=
    LspInfoBorder                               { fg="#78a9ff", }, -- LspInfoBorder  xxx guifg=#78a9ff
    HighlightUndo                               { fg="#dcd7ba", bg="#2d4f67", }, -- HighlightUndo  xxx cterm= gui= guifg=#dcd7ba guibg=#2d4f67

    IblIndent                                   { fg="#313244", }, -- IblIndent      xxx guifg=#313244
    IblScope                                    { fg="#cdd6f4", }, -- IblScope       xxx guifg=#cdd6f4

    sym"@ibl.indent.char.1"                     { fg="#313244", gui="nocombine", }, -- @ibl.indent.char.1 xxx cterm=nocombine gui=nocombine guifg=#313244
    sym"@ibl.whitespace.char.1"                 { gui="nocombine", }, -- @ibl.whitespace.char.1 xxx cterm=nocombine gui=nocombine
    sym"@ibl.scope.char.1"                      { fg="#cdd6f4", gui="nocombine", }, -- @ibl.scope.char.1 xxx cterm=nocombine gui=nocombine guifg=#cdd6f4
    sym"@ibl.scope.underline.1"                 { sp="#cdd6f4", gui="underline", }, -- @ibl.scope.underline.1 xxx cterm=underline gui=underline guisp=#cdd6f4

    -- TelescopePromptPrefix                       { }, -- TelescopePromptPrefix xxx cterm= gui=
    -- TelescopeMatching                           { fg="#78a9ff", }, -- TelescopeMatching xxx guifg=#78a9ff
    -- TelescopePromptCounter                      { }, -- TelescopePromptCounter xxx cterm= gui=
    -- TelescopePreviewTitle                       { fg="#abe9b3", }, -- TelescopePreviewTitle xxx guifg=#abe9b3
    -- TelescopeTitle                              { }, -- TelescopeTitle xxx cterm= gui=
    -- TelescopeResultsTitle                       { fg="#ff9e64", }, -- TelescopeResultsTitle xxx guifg=#ff9e64
    -- TelescopePromptTitle                        { fg="#e95678", }, -- TelescopePromptTitle xxx guifg=#e95678
    -- TelescopeNormal                             { bg="#0d0c14", }, -- TelescopeNormal xxx guibg=#0d0c14
    -- TelescopePreviewBorder                      { }, -- TelescopePreviewBorder xxx cterm= gui=
    -- TelescopeResultsBorder                      { }, -- TelescopeResultsBorder xxx cterm= gui=
    -- TelescopePromptBorder                       { }, -- TelescopePromptBorder xxx cterm= gui=
    -- TelescopeResultsNormal                      { }, -- TelescopeResultsNormal xxx cterm= gui=
    -- TelescopePromptNormal                       { }, -- TelescopePromptNormal xxx cterm= gui=
    -- TelescopeMultiIcon                          { }, -- TelescopeMultiIcon xxx cterm= gui=
    -- TelescopeMultiSelection                     { }, -- TelescopeMultiSelection xxx cterm= gui=
    -- TelescopeSelectionCaret                     { fg="#f2cdcd", }, -- TelescopeSelectionCaret xxx guifg=#f2cdcd
    -- TelescopeSelection                          { fg="#cdd6f4", gui="bold", bg="#313244", }, -- TelescopeSelection xxx cterm=bold gui=bold guifg=#cdd6f4 guibg=#313244
    -- TelescopeResultsDiffUntracked               { }, -- TelescopeResultsDiffUntracked xxx cterm= gui=
    -- TelescopeResultsDiffDelete                  { }, -- TelescopeResultsDiffDelete xxx cterm= gui=
    -- TelescopeResultsDiffAdd                     { }, -- TelescopeResultsDiffAdd xxx cterm= gui=
    -- TelescopeResultsDiffChange                  { }, -- TelescopeResultsDiffChange xxx cterm= gui=
    -- TelescopeResultsSpecialComment              { }, -- TelescopeResultsSpecialComment xxx cterm= gui=
    -- TelescopeResultsComment                     { }, -- TelescopeResultsComment xxx cterm= gui=
    -- TelescopeResultsNumber                      { }, -- TelescopeResultsNumber xxx cterm= gui=
    -- TelescopeResultsIdentifier                  { }, -- TelescopeResultsIdentifier xxx cterm= gui=
    -- TelescopeResultsLineNr                      { }, -- TelescopeResultsLineNr xxx cterm= gui=
    -- TelescopeResultsVariable                    { }, -- TelescopeResultsVariable xxx cterm= gui=
    -- TelescopeResultsStruct                      { }, -- TelescopeResultsStruct xxx cterm= gui=
    -- TelescopeResultsOperator                    { }, -- TelescopeResultsOperator xxx cterm= gui=
    -- TelescopeResultsMethod                      { }, -- TelescopeResultsMethod xxx cterm= gui=
    -- TelescopeResultsFunction                    { }, -- TelescopeResultsFunction xxx cterm= gui=
    -- TelescopeResultsField                       { }, -- TelescopeResultsField xxx cterm= gui=
    -- TelescopeResultsConstant                    { }, -- TelescopeResultsConstant xxx cterm= gui=
    -- TelescopeResultsClass                       { }, -- TelescopeResultsClass xxx cterm= gui=
    -- TelescopePreviewMessageFillchar             { }, -- TelescopePreviewMessageFillchar xxx cterm= gui=
    -- TelescopePreviewMessage                     { }, -- TelescopePreviewMessage xxx cterm= gui=
    -- TelescopePreviewNormal                      { }, -- TelescopePreviewNormal xxx cterm= gui=
    -- TelescopePreviewDate                        { }, -- TelescopePreviewDate xxx cterm= gui=
    -- TelescopePreviewGroup                       { }, -- TelescopePreviewGroup xxx cterm= gui=
    -- TelescopePreviewUser                        { }, -- TelescopePreviewUser xxx cterm= gui=
    -- TelescopePreviewSize                        { }, -- TelescopePreviewSize xxx cterm= gui=
    -- TelescopePreviewSticky                      { }, -- TelescopePreviewSticky xxx cterm= gui=
    -- TelescopePreviewHyphen                      { }, -- TelescopePreviewHyphen xxx cterm= gui=
    -- TelescopePreviewExecute                     { }, -- TelescopePreviewExecute xxx cterm= gui=
    -- TelescopePreviewWrite                       { }, -- TelescopePreviewWrite xxx cterm= gui=
    -- TelescopePreviewRead                        { }, -- TelescopePreviewRead xxx cterm= gui=
    -- TelescopePreviewSocket                      { }, -- TelescopePreviewSocket xxx cterm= gui=
    -- TelescopePreviewLink                        { }, -- TelescopePreviewLink xxx cterm= gui=
    -- TelescopePreviewBlock                       { }, -- TelescopePreviewBlock xxx cterm= gui=
    -- TelescopePreviewDirectory                   { }, -- TelescopePreviewDirectory xxx cterm= gui=
    -- TelescopePreviewCharDev                     { }, -- TelescopePreviewCharDev xxx cterm= gui=
    -- TelescopePreviewPipe                        { }, -- TelescopePreviewPipe xxx cterm= gui=
    -- TelescopePreviewMatch                       { }, -- TelescopePreviewMatch xxx cterm= gui=
    -- TelescopePreviewLine                        { }, -- TelescopePreviewLine xxx cterm= gui=

    CmpItemAbbr                                 { fg="#9399b2", }, -- CmpItemAbbr    xxx guifg=#9399b2
    CmpItemAbbrDefault                          { fg="#cdd6f4", }, -- CmpItemAbbrDefault xxx guifg=#cdd6f4
    CmpItemAbbrDeprecated                       { fg="#6c7086", gui="strikethrough", }, -- CmpItemAbbrDeprecated xxx cterm=strikethrough gui=strikethrough guifg=#6c7086
    CmpItemAbbrDeprecatedDefault                { fg="#6c7086", }, -- CmpItemAbbrDeprecatedDefault xxx guifg=#6c7086
    CmpItemAbbrMatch                            { fg="#cdd6f4", gui="bold", }, -- CmpItemAbbrMatch xxx cterm=bold gui=bold guifg=#cdd6f4
    CmpItemAbbrMatchDefault                     { fg="#cdd6f4", }, -- CmpItemAbbrMatchDefault xxx guifg=#cdd6f4
    CmpItemAbbrMatchFuzzy                       { fg="#cdd6f4", gui="bold", }, -- CmpItemAbbrMatchFuzzy xxx cterm=bold gui=bold guifg=#cdd6f4
    CmpItemAbbrMatchFuzzyDefault                { fg="#cdd6f4", }, -- CmpItemAbbrMatchFuzzyDefault xxx guifg=#cdd6f4
    CmpItemKind                                 { fg="#78a9ff", }, -- CmpItemKind    xxx guifg=#78a9ff
    CmpItemKindOperatorDefault                  { CmpItemKind }, -- CmpItemKindOperatorDefault xxx links to CmpItemKind
    CmpItemKindModuleDefault                    { CmpItemKind }, -- CmpItemKindModuleDefault xxx links to CmpItemKind
    CmpItemKindTypeParameterDefault             { CmpItemKind }, -- CmpItemKindTypeParameterDefault xxx links to CmpItemKind
    CmpItemKindStructDefault                    { CmpItemKind }, -- CmpItemKindStructDefault xxx links to CmpItemKind
    CmpItemKindEnumMemberDefault                { CmpItemKind }, -- CmpItemKindEnumMemberDefault xxx links to CmpItemKind
    CmpItemKindFileDefault                      { CmpItemKind }, -- CmpItemKindFileDefault xxx links to CmpItemKind
    CmpItemKindEnumDefault                      { CmpItemKind }, -- CmpItemKindEnumDefault xxx links to CmpItemKind
    CmpItemKindTextDefault                      { CmpItemKind }, -- CmpItemKindTextDefault xxx links to CmpItemKind
    CmpItemKindUnitDefault                      { CmpItemKind }, -- CmpItemKindUnitDefault xxx links to CmpItemKind
    CmpItemKindValueDefault                     { CmpItemKind }, -- CmpItemKindValueDefault xxx links to CmpItemKind
    CmpItemKindFolderDefault                    { CmpItemKind }, -- CmpItemKindFolderDefault xxx links to CmpItemKind
    CmpItemKindColorDefault                     { CmpItemKind }, -- CmpItemKindColorDefault xxx links to CmpItemKind
    CmpItemKindKeywordDefault                   { CmpItemKind }, -- CmpItemKindKeywordDefault xxx links to CmpItemKind
    CmpItemKindClassDefault                     { CmpItemKind }, -- CmpItemKindClassDefault xxx links to CmpItemKind
    CmpItemKindSnippetDefault                   { CmpItemKind }, -- CmpItemKindSnippetDefault xxx links to CmpItemKind
    CmpItemKindPropertyDefault                  { CmpItemKind }, -- CmpItemKindPropertyDefault xxx links to CmpItemKind
    CmpItemKindConstantDefault                  { CmpItemKind }, -- CmpItemKindConstantDefault xxx links to CmpItemKind
    CmpItemKindFunctionDefault                  { CmpItemKind }, -- CmpItemKindFunctionDefault xxx links to CmpItemKind
    CmpItemKindReferenceDefault                 { CmpItemKind }, -- CmpItemKindReferenceDefault xxx links to CmpItemKind
    CmpItemKindInterfaceDefault                 { CmpItemKind }, -- CmpItemKindInterfaceDefault xxx links to CmpItemKind
    CmpItemKindVariableDefault                  { CmpItemKind }, -- CmpItemKindVariableDefault xxx links to CmpItemKind
    CmpItemKindFieldDefault                     { CmpItemKind }, -- CmpItemKindFieldDefault xxx links to CmpItemKind
    CmpItemKindConstructorDefault               { CmpItemKind }, -- CmpItemKindConstructorDefault xxx links to CmpItemKind
    CmpItemKindMethodDefault                    { CmpItemKind }, -- CmpItemKindMethodDefault xxx links to CmpItemKind
    CmpItemKindEventDefault                     { CmpItemKind }, -- CmpItemKindEventDefault xxx links to CmpItemKind
    CmpItemKindDefault                          { fg="#7dcfff", }, -- CmpItemKindDefault xxx guifg=#7dcfff
    CmpItemMenu                                 { fg="#cdd6f4", }, -- CmpItemMenu    xxx guifg=#cdd6f4
    CmpItemMenuDefault                          { fg="#cdd6f4", }, -- CmpItemMenuDefault xxx guifg=#cdd6f4
    CmpItemKindOperator                         { fg="#78a9ff", }, -- CmpItemKindOperator xxx guifg=#78a9ff
    CmpItemKindModule                           { fg="#78a9ff", }, -- CmpItemKindModule xxx guifg=#78a9ff
    CmpItemKindTypeParameter                    { fg="#78a9ff", }, -- CmpItemKindTypeParameter xxx guifg=#78a9ff
    CmpItemKindStruct                           { fg="#78a9ff", }, -- CmpItemKindStruct xxx guifg=#78a9ff
    CmpItemKindEnumMember                       { fg="#e95678", }, -- CmpItemKindEnumMember xxx guifg=#e95678
    CmpItemKindFile                             { fg="#78a9ff", }, -- CmpItemKindFile xxx guifg=#78a9ff
    CmpItemKindEnum                             { fg="#abe9b3", }, -- CmpItemKindEnum xxx guifg=#abe9b3
    CmpItemKindText                             { fg="#b5e8e0", }, -- CmpItemKindText xxx guifg=#b5e8e0
    CmpItemKindUnit                             { fg="#abe9b3", }, -- CmpItemKindUnit xxx guifg=#abe9b3
    CmpItemKindValue                            { fg="#ff9d64", }, -- CmpItemKindValue xxx guifg=#ff9d64
    CmpItemKindFolder                           { fg="#78a9ff", }, -- CmpItemKindFolder xxx guifg=#78a9ff
    CmpItemKindColor                            { fg="#e95678", }, -- CmpItemKindColor xxx guifg=#e95678
    CmpItemKindKeyword                          { fg="#e95678", }, -- CmpItemKindKeyword xxx guifg=#e95678
    CmpItemKindClass                            { fg="#fae3b0", }, -- CmpItemKindClass xxx guifg=#fae3b0
    CmpItemKindSnippet                          { fg="#9d7dd8", }, -- CmpItemKindSnippet xxx guifg=#9d7dd8
    CmpItemKindProperty                         { fg="#abe9b3", }, -- CmpItemKindProperty xxx guifg=#abe9b3
    CmpItemKindConstant                         { fg="#ff9d64", }, -- CmpItemKindConstant xxx guifg=#ff9d64
    CmpItemKindFunction                         { fg="#78a9ff", }, -- CmpItemKindFunction xxx guifg=#78a9ff
    CmpItemKindReference                        { fg="#e95678", }, -- CmpItemKindReference xxx guifg=#e95678
    CmpItemKindInterface                        { fg="#fae3b0", }, -- CmpItemKindInterface xxx guifg=#fae3b0
    CmpItemKindVariable                         { fg="#f2cdcd", }, -- CmpItemKindVariable xxx guifg=#f2cdcd
    CmpItemKindField                            { fg="#abe9b3", }, -- CmpItemKindField xxx guifg=#abe9b3
    CmpItemKindConstructor                      { fg="#78a9ff", }, -- CmpItemKindConstructor xxx guifg=#78a9ff
    CmpItemKindMethod                           { fg="#78a9ff", }, -- CmpItemKindMethod xxx guifg=#78a9ff
    CmpItemKindEvent                            { fg="#78a9ff", }, -- CmpItemKindEvent xxx guifg=#78a9ff

    MiniSurround                                { }, -- MiniSurround   xxx cterm= gui=

    NvimTreeWindowPicker                        { fg="#e95678", bg="#13121a", }, -- NvimTreeWindowPicker xxx guifg=#e95678 guibg=#13121a
    NvimTreeGitNew                              { fg="#fae3b0", }, -- NvimTreeGitNew xxx guifg=#fae3b0
    NvimTreeFileNew                             { NvimTreeGitNew }, -- NvimTreeFileNew xxx links to NvimTreeGitNew
    NvimTreeGitRenamed                          { fg="#ff80ff", }, -- NvimTreeGitRenamed xxx guifg=#ff80ff
    NvimTreeFileRenamed                         { NvimTreeGitRenamed }, -- NvimTreeFileRenamed xxx links to NvimTreeGitRenamed
    NvimTreeGitMerge                            { fg="#ffa0a0", }, -- NvimTreeGitMerge xxx guifg=#ffa0a0
    NvimTreeFileMerge                           { NvimTreeGitMerge }, -- NvimTreeFileMerge xxx links to NvimTreeGitMerge
    NvimTreeGitStaged                           { fg="#ffa0a0", }, -- NvimTreeGitStaged xxx guifg=#ffa0a0
    NvimTreeFileStaged                          { NvimTreeGitStaged }, -- NvimTreeFileStaged xxx links to NvimTreeGitStaged
    NvimTreeGitDeleted                          { fg="#e95678", }, -- NvimTreeGitDeleted xxx guifg=#e95678
    NvimTreeFileDeleted                         { NvimTreeGitDeleted }, -- NvimTreeFileDeleted xxx links to NvimTreeGitDeleted
    NvimTreeGitDirty                            { fg="#fae3b0", }, -- NvimTreeGitDirty xxx guifg=#fae3b0
    NvimTreeFileDirty                           { NvimTreeGitDirty }, -- NvimTreeFileDirty xxx links to NvimTreeGitDirty
    NvimTreeModifiedFile                        { fg="#ffa0a0", }, -- NvimTreeModifiedFile xxx guifg=#ffa0a0
    NvimTreeOpenedFile                          { fg="#f5c2e7", }, -- NvimTreeOpenedFile xxx guifg=#f5c2e7
    NvimTreeOpenedFileIcon                      { NvimTreeOpenedFile }, -- NvimTreeOpenedFileIcon xxx links to NvimTreeOpenedFile
    NvimTreeImageFile                           { fg="#cdd6f4", }, -- NvimTreeImageFile xxx guifg=#cdd6f4
    NvimTreeSpecialFile                         { fg="#fae3b0", gui="bold", }, -- NvimTreeSpecialFile xxx cterm=bold gui=bold guifg=#fae3b0
    NvimTreeExecFile                            { fg="#ffa0a0", gui="bold", }, -- NvimTreeExecFile xxx gui=bold guifg=#ffa0a0
    NvimTreeRootFolder                          { fg="#e95678", gui="bold", }, -- NvimTreeRootFolder xxx cterm=bold gui=bold guifg=#e95678
    NvimTreeFolderIcon                          { fg="#78a9ff", }, -- NvimTreeFolderIcon xxx guifg=#78a9ff
    NvimTreeClosedFolderIcon                    { NvimTreeFolderIcon }, -- NvimTreeClosedFolderIcon xxx links to NvimTreeFolderIcon
    NvimTreeOpenedFolderIcon                    { NvimTreeFolderIcon }, -- NvimTreeOpenedFolderIcon xxx links to NvimTreeFolderIcon
    NvimTreeSymlink                             { fg="#f5c2e7", }, -- NvimTreeSymlink xxx guifg=#f5c2e7
    NvimTreeIndentMarker                        { fg="#4e4d5d", }, -- NvimTreeIndentMarker xxx guifg=#4e4d5d
    NvimTreeBookmark                            { fg="#ffa0a0", }, -- NvimTreeBookmark xxx guifg=#ffa0a0
    NvimTreeLiveFilterValue                     { gui="bold", }, -- NvimTreeLiveFilterValue xxx gui=bold
    NvimTreeLiveFilterPrefix                    { fg="#ff80ff", gui="bold", }, -- NvimTreeLiveFilterPrefix xxx gui=bold guifg=#ff80ff
    NvimTreeWinSeparator                        { fg="#0d0c14", bg="#0d0c14", }, -- NvimTreeWinSeparator xxx guifg=#0d0c14 guibg=#0d0c14
    NvimTreeCursorLine                          { bg="#13121a", }, -- NvimTreeCursorLine xxx guibg=#13121a
    NvimTreeNormalNC                            { bg="#0d0c14", }, -- NvimTreeNormalNC xxx guibg=#0d0c14
    NvimTreeNormal                              { fg="#cdd6f4", bg="#0d0c14", }, -- NvimTreeNormal xxx guifg=#cdd6f4 guibg=#0d0c14
    NvimTreeSignColumn                          { NvimTreeNormal }, -- NvimTreeSignColumn xxx links to NvimTreeNormal
    NvimTreeOpenedFolderName                    { fg="#78a9ff", }, -- NvimTreeOpenedFolderName xxx guifg=#78a9ff
    NvimTreeEmptyFolderName                     { fg="#78a9ff", }, -- NvimTreeEmptyFolderName xxx guifg=#78a9ff
    NvimTreeFolderName                          { fg="#78a9ff", }, -- NvimTreeFolderName xxx guifg=#78a9ff
    NvimTreeGitIgnored                          { fg="#605f6f", }, -- NvimTreeGitIgnored xxx guifg=#605f6f
    NvimTreeFileIgnored                         { NvimTreeGitIgnored }, -- NvimTreeFileIgnored xxx links to NvimTreeGitIgnored
    NvimTreeStatusLineNC                        { fg="#181825", bg="#181825", }, -- NvimTreeStatusLineNC xxx guifg=#181825 guibg=#181825
    LspReferenceWrite                           { bg="#45475a", }, -- LspReferenceWrite xxx guibg=#45475a
    LspReferenceRead                            { bg="#45475a", }, -- LspReferenceRead xxx guibg=#45475a
    LspReferenceText                            { bg="#45475a", }, -- LspReferenceText xxx guibg=#45475a
    Bold                                        { gui="bold", }, -- Bold           xxx cterm=bold gui=bold
    LspDiagnosticsHint                          { fg="#b5e8e0", }, -- LspDiagnosticsHint xxx guifg=#b5e8e0
    LspDiagnosticsInformation                   { fg="#89dceb", }, -- LspDiagnosticsInformation xxx guifg=#89dceb
    LspDiagnosticsWarning                       { fg="#fae3b0", }, -- LspDiagnosticsWarning xxx guifg=#fae3b0
    LspDiagnosticsError                         { fg="#e95678", }, -- LspDiagnosticsError xxx guifg=#e95678
    LspDiagnosticsUnderlineHint                 { sp="#b5e8e0", gui="underline", }, -- LspDiagnosticsUnderlineHint xxx cterm=underline gui=underline guisp=#b5e8e0
    LspKindOperator                             { fg="#89dceb", }, -- LspKindOperator xxx guifg=#89dceb
    LspKindNumber                               { fg="#ff9d64", }, -- LspKindNumber  xxx guifg=#ff9d64
    LspKindNamespace                            { fg="#78a9ff", }, -- LspKindNamespace xxx guifg=#78a9ff
    LspKindModule                               { fg="#78a9ff", }, -- LspKindModule  xxx guifg=#78a9ff
    LspKindMethod                               { fg="#78a9ff", }, -- LspKindMethod  xxx guifg=#78a9ff
    LspKindKey                                  { fg="#e95678", }, -- LspKindKey     xxx guifg=#e95678
    LspKindInterface                            { fg="#fae3b0", }, -- LspKindInterface xxx guifg=#fae3b0
    LspKindFunction                             { fg="#78a9ff", }, -- LspKindFunction xxx guifg=#78a9ff
    LspKindFile                                 { fg="#f5e0dc", }, -- LspKindFile    xxx guifg=#f5e0dc
    LspKindField                                { fg="#b5e8e0", }, -- LspKindField   xxx guifg=#b5e8e0
    LspKindEvent                                { fg="#fae3b0", }, -- LspKindEvent   xxx guifg=#fae3b0
    LspKindEnumMember                           { fg="#b5e8e0", }, -- LspKindEnumMember xxx guifg=#b5e8e0
    LspKindEnum                                 { fg="#fae3b0", }, -- LspKindEnum    xxx guifg=#fae3b0
    LspKindConstructor                          { fg="#74c7ec", }, -- LspKindConstructor xxx guifg=#74c7ec
    LspKindConstant                             { fg="#ff9d64", }, -- LspKindConstant xxx guifg=#ff9d64
    LspKindClass                                { fg="#fae3b0", }, -- LspKindClass   xxx guifg=#fae3b0
    OutlineIndent                               { fg="#9399b2", }, -- OutlineIndent  xxx guifg=#9399b2
    SagaShadow                                  { bg="#11111b", }, -- SagaShadow     xxx guibg=#11111b
    CallHierarchyTitle                          { fg="#78a9ff", }, -- CallHierarchyTitle xxx guifg=#78a9ff
    CallHierarchyIcon                           { fg="#9d7dd8", }, -- CallHierarchyIcon xxx guifg=#9d7dd8
    DiagnosticFname                             { fg="#cdd6f4", }, -- DiagnosticFname xxx guifg=#cdd6f4
    DiagnosticText                              { fg="#cdd6f4", }, -- DiagnosticText xxx guifg=#cdd6f4
    DiagnosticSource                            { fg="#6c7086", }, -- DiagnosticSource xxx guifg=#6c7086
    RenameNormal                                { fg="#cdd6f4", }, -- RenameNormal   xxx guifg=#cdd6f4
    FinderStart                                 { fg="#b5e8e0", gui="bold", }, -- FinderStart    xxx cterm=bold gui=bold guifg=#b5e8e0
    FinderSpinner                               { fg="#9d7dd8", gui="bold", }, -- FinderSpinner  xxx cterm=bold gui=bold guifg=#9d7dd8
    FinderSpinnerTitle                          { fg="#9d7dd8", gui="bold", }, -- FinderSpinnerTitle xxx cterm=bold gui=bold guifg=#9d7dd8
    FinderType                                  { fg="#f2cdcd", }, -- FinderType     xxx guifg=#f2cdcd
    FinderIcon                                  { fg="#f2cdcd", }, -- FinderIcon     xxx guifg=#f2cdcd
    FinderCode                                  { fg="#cdd6f4", }, -- FinderCode     xxx guifg=#cdd6f4
    FinderFName                                 { fg="#a6adc8", gui="bold", }, -- FinderFName    xxx cterm=bold gui=bold guifg=#a6adc8
    FinderSelection                             { fg="#78a9ff", gui="bold", }, -- FinderSelection xxx cterm=bold gui=bold guifg=#78a9ff
    CodeActionNumber                            { fg="#f5c2e7", }, -- CodeActionNumber xxx guifg=#f5c2e7
    CodeActionText                              { fg="#abe9b3", }, -- CodeActionText xxx guifg=#abe9b3
    ActionPreviewTitle                          { fg="#9d7dd8", bg="#0f0f17", }, -- ActionPreviewTitle xxx guifg=#9d7dd8 guibg=#0f0f17
    ActionFix                                   { fg="#f5c2e7", }, -- ActionFix      xxx guifg=#f5c2e7
    SagaBeacon                                  { bg="#2b2b3c", }, -- SagaBeacon     xxx guibg=#2b2b3c
    SagaCount                                   { fg="#7f849c", }, -- SagaCount      xxx guifg=#7f849c
    SagaCollapse                                { fg="#abe9b3", }, -- SagaCollapse   xxx guifg=#abe9b3
    SagaExpand                                  { fg="#abe9b3", }, -- SagaExpand     xxx guifg=#abe9b3
    SagaNormal                                  { bg="#0f0f17", }, -- SagaNormal     xxx guibg=#0f0f17
    SagaBorder                                  { fg="#78a9ff", }, -- SagaBorder     xxx guifg=#78a9ff
    TitleIcon                                   { fg="#78a9ff", }, -- TitleIcon      xxx guifg=#78a9ff
    TitleString                                 { fg="#cdd6f4", }, -- TitleString    xxx guifg=#cdd6f4
    GlyphPalette9                               { fg="#e95678", }, -- GlyphPalette9  xxx guifg=#e95678
    CmpItemKindCopilot                          { fg="#b5e8e0", }, -- CmpItemKindCopilot xxx guifg=#b5e8e0
    diffLine                                    { fg="#6c7086", }, -- diffLine       xxx guifg=#6c7086
    IndentBlanklineIndent5                      { fg="#e95678", blend=0, }, -- IndentBlanklineIndent5 xxx guifg=#e95678 blend=0
    IlluminatedWordWrite                        { bg="#353646", }, -- IlluminatedWordWrite xxx guibg=#353646
    mkdCodeStart                                { fg="#f2cdcd", gui="bold", }, -- mkdCodeStart   xxx cterm=bold gui=bold guifg=#f2cdcd
    qfLineNr                                    { fg="#fae3b0", }, -- qfLineNr       xxx guifg=#fae3b0
    DapUIUnavailable                            { fg="#45475a", }, -- DapUIUnavailable xxx guifg=#45475a
    DapUIRestart                                { fg="#abe9b3", }, -- DapUIRestart   xxx guifg=#abe9b3
    DapUIPlayPause                              { fg="#abe9b3", }, -- DapUIPlayPause xxx guifg=#abe9b3
    DapUIStop                                   { fg="#e95678", }, -- DapUIStop      xxx guifg=#e95678
    DapUIStepOut                                { fg="#78a9ff", }, -- DapUIStepOut   xxx guifg=#78a9ff
    DapUIStepBack                               { fg="#78a9ff", }, -- DapUIStepBack  xxx guifg=#78a9ff
    DapUIStepInto                               { fg="#78a9ff", }, -- DapUIStepInto  xxx guifg=#78a9ff
    DapUIStepOver                               { fg="#78a9ff", }, -- DapUIStepOver  xxx guifg=#78a9ff
    DapUIBreakpointsDisabledLine                { fg="#585b70", }, -- DapUIBreakpointsDisabledLine xxx guifg=#585b70
    DapUIBreakpointsCurrentLine                 { fg="#abe9b3", gui="bold", }, -- DapUIBreakpointsCurrentLine xxx cterm=bold gui=bold guifg=#abe9b3
    DapUIBreakpointsPath                        { fg="#89dceb", }, -- DapUIBreakpointsPath xxx guifg=#89dceb
    sym"@scope"                                 { gui="bold", }, -- @scope         xxx cterm=bold gui=bold
    DapUIWatchesEmpty                           { fg="#da4b4a", }, -- DapUIWatchesEmpty xxx guifg=#da4b4a
    DapUIFloatBorder                            { fg="#89dceb", }, -- DapUIFloatBorder xxx guifg=#89dceb
    DapUILineNumber                             { fg="#89dceb", }, -- DapUILineNumber xxx guifg=#89dceb
    sym"@variable.builtin"                      { fg="#7dcfff", }, -- @variable.builtin xxx guifg=#7dcfff
    sym"@lsp.typemod.variable.defaultLibrary"   { sym"@variable.builtin" }, -- @lsp.typemod.variable.defaultLibrary xxx links to @variable.builtin
    DapUIThread                                 { fg="#abe9b3", }, -- DapUIThread    xxx guifg=#abe9b3
    DapUIDecoration                             { fg="#89dceb", }, -- DapUIDecoration xxx guifg=#89dceb
    DapUIModifiedValue                          { fg="#ff9d64", }, -- DapUIModifiedValue xxx guifg=#ff9d64
    DAPUIVariable                               { fg="#cdd6f4", }, -- DAPUIVariable  xxx guifg=#cdd6f4
    DAPUIValue                                  { fg="#89dceb", }, -- DAPUIValue     xxx guifg=#89dceb
    DAPUIType                                   { fg="#9d7dd8", }, -- DAPUIType      xxx guifg=#9d7dd8
    DAPUIScope                                  { fg="#89dceb", }, -- DAPUIScope     xxx guifg=#89dceb
    DapLogPoint                                 { fg="#89dceb", }, -- DapLogPoint    xxx guifg=#89dceb
    DapBreakpointCondition                      { fg="#fae3b0", }, -- DapBreakpointCondition xxx guifg=#fae3b0
    DapBreakpoint                               { fg="#e95678", }, -- DapBreakpoint  xxx guifg=#e95678
    NormalSB                                    { fg="#cdd6f4", bg="#11111b", }, -- NormalSB       xxx guifg=#cdd6f4 guibg=#11111b
    SignColumnSB                                { fg="#45475a", bg="#11111b", }, -- SignColumnSB   xxx guifg=#45475a guibg=#11111b
    -- NotifyTRACETitle                            { fg="#f5e0dc", gui="italic", }, -- NotifyTRACETitle xxx cterm=italic gui=italic guifg=#f5e0dc
    -- NotifyTRACEIcon                             { fg="#f5e0dc", }, -- NotifyTRACEIcon xxx guifg=#f5e0dc
    -- NotifyTRACEBorder                           { fg="#f5e0dc", }, -- NotifyTRACEBorder xxx guifg=#f5e0dc
    -- NotifyDEBUGTitle                            { fg="#ff9d64", gui="italic", }, -- NotifyDEBUGTitle xxx cterm=italic gui=italic guifg=#ff9d64
    VimwikiHeader6                              { fg="#9d7dd8", gui="bold", }, -- VimwikiHeader6 xxx cterm=bold gui=bold guifg=#9d7dd8
    markdownH6                                  { fg="#b5e8e0", }, -- markdownH6     xxx guifg=#b5e8e0
    NotifyINFOTitle                             { fg="#78a9ff", gui="italic", }, -- NotifyINFOTitle xxx cterm=italic gui=italic guifg=#78a9ff
    NotifyINFOIcon                              { fg="#78a9ff", }, -- NotifyINFOIcon xxx guifg=#78a9ff
    NotifyINFOBorder                            { fg="#78a9ff", }, -- NotifyINFOBorder xxx guifg=#78a9ff
    markdownH2                                  { fg="#9d7dd8", }, -- markdownH2     xxx guifg=#9d7dd8
    VimwikiTag                                  { fg="#ff9d64", }, -- VimwikiTag     xxx guifg=#ff9d64
    markdownCodeBlock                           { fg="#f2cdcd", }, -- markdownCodeBlock xxx guifg=#f2cdcd
    NotifyERRORIcon                             { fg="#e95678", }, -- NotifyERRORIcon xxx guifg=#e95678
    NotifyERRORBorder                           { fg="#e95678", }, -- NotifyERRORBorder xxx guifg=#e95678
    VimwikiLink                                 { fg="#89dceb", }, -- VimwikiLink    xxx guifg=#89dceb
    FidgetTitle                                 { fg="#78a9ff", }, -- FidgetTitle    xxx guifg=#78a9ff
    FidgetTask                                  { fg="#cdd6f4", bg="#181825", }, -- FidgetTask     xxx guifg=#cdd6f4 guibg=#181825
    LspCodeLens                                 { fg="#6c7086", }, -- LspCodeLens    xxx guifg=#6c7086
    LspKindValue                                { fg="#ff9d64", }, -- LspKindValue   xxx guifg=#ff9d64
    LspKindUnit                                 { fg="#abe9b3", }, -- LspKindUnit    xxx guifg=#abe9b3
    LspKindFolder                               { fg="#78a9ff", }, -- LspKindFolder  xxx guifg=#78a9ff
    LspKindSnippet                              { fg="#9d7dd8", }, -- LspKindSnippet xxx guifg=#9d7dd8
    LspKindText                                 { fg="#abe9b3", }, -- LspKindText    xxx guifg=#abe9b3
    LspKindStaticMethod                         { fg="#ff9d64", }, -- LspKindStaticMethod xxx guifg=#ff9d64
    LspKindParameter                            { fg="#78a9ff", }, -- LspKindParameter xxx guifg=#78a9ff
    LspKindTypeAlias                            { fg="#abe9b3", }, -- LspKindTypeAlias xxx guifg=#abe9b3
    LspKindString                               { fg="#abe9b3", }, -- LspKindString  xxx guifg=#abe9b3
    LspKindObject                               { fg="#fae3b0", }, -- LspKindObject  xxx guifg=#fae3b0
    LspKindNull                                 { fg="#fae3b0", }, -- LspKindNull    xxx guifg=#fae3b0
    LspKindBoolean                              { fg="#ff9d64", }, -- LspKindBoolean xxx guifg=#ff9d64
    LspKindArray                                { fg="#ff9d64", }, -- LspKindArray   xxx guifg=#ff9d64
    LspKindVariable                             { fg="#ff9d64", }, -- LspKindVariable xxx guifg=#ff9d64
    LspKindTypeParameter                        { fg="#da4b4a", }, -- LspKindTypeParameter xxx guifg=#da4b4a
    LspKindStruct                               { fg="#fae3b0", }, -- LspKindStruct  xxx guifg=#fae3b0
    LspKindProperty                             { fg="#b5e8e0", }, -- LspKindProperty xxx guifg=#b5e8e0
    LspKindPackage                              { fg="#78a9ff", }, -- LspKindPackage xxx guifg=#78a9ff
    LspDiagnosticsDefaultError                  { fg="#e95678", }, -- LspDiagnosticsDefaultError xxx guifg=#e95678
    LspDiagnosticsDefaultWarning                { fg="#fae3b0", }, -- LspDiagnosticsDefaultWarning xxx guifg=#fae3b0
    LspDiagnosticsDefaultInformation            { fg="#89dceb", }, -- LspDiagnosticsDefaultInformation xxx guifg=#89dceb
    LspDiagnosticsDefaultHint                   { fg="#b5e8e0", }, -- LspDiagnosticsDefaultHint xxx guifg=#b5e8e0
    sym"@keyword.operator"                      { fg="#be95ff", gui="bold", }, -- @keyword.operator xxx cterm=bold gui=bold guifg=#be95ff
    GlyphPalette7                               { fg="#cdd6f4", }, -- GlyphPalette7  xxx guifg=#cdd6f4
    qfFileName                                  { fg="#78a9ff", }, -- qfFileName     xxx guifg=#78a9ff
    htmlH1                                      { fg="#f5c2e7", gui="bold", }, -- htmlH1         xxx cterm=bold gui=bold guifg=#f5c2e7
    htmlH2                                      { fg="#78a9ff", gui="bold", }, -- htmlH2         xxx cterm=bold gui=bold guifg=#78a9ff
    mkdCodeDelimiter                            { fg="#cdd6f4", bg="#0f0f17", }, -- mkdCodeDelimiter xxx guifg=#cdd6f4 guibg=#0f0f17
    mkdCodeEnd                                  { fg="#f2cdcd", gui="bold", }, -- mkdCodeEnd     xxx cterm=bold gui=bold guifg=#f2cdcd
    debugPC                                     { bg="#11111b", }, -- debugPC        xxx guibg=#11111b
    debugBreakpoint                             { fg="#6c7086", bg="#0f0f17", }, -- debugBreakpoint xxx guifg=#6c7086 guibg=#0f0f17
    illuminatedWord                             { bg="#45475a", }, -- illuminatedWord xxx guibg=#45475a
    illuminatedCurWord                          { bg="#45475a", }, -- illuminatedCurWord xxx guibg=#45475a
    MasonHeading                                { gui="bold", }, -- MasonHeading   xxx cterm=bold gui=bold
    MasonError                                  { fg="#e95678", }, -- MasonError     xxx guifg=#e95678
    MasonMutedBlockBold                         { fg="#0f0f17", gui="bold", bg="#fae3b0", }, -- MasonMutedBlockBold xxx cterm=bold gui=bold guifg=#0f0f17 guibg=#fae3b0
    MasonMuted                                  { fg="#6c7086", }, -- MasonMuted     xxx guifg=#6c7086
    MasonHighlightBlockBoldSecondary            { fg="#0f0f17", gui="bold", }, -- MasonHighlightBlockBoldSecondary xxx cterm=bold gui=bold guifg=#0f0f17
    MasonHighlightBlockSecondary                { fg="#0f0f17", bg="#78a9ff", }, -- MasonHighlightBlockSecondary xxx guifg=#0f0f17 guibg=#78a9ff
    MasonHighlightSecondary                     { fg="#9d7dd8", }, -- MasonHighlightSecondary xxx guifg=#9d7dd8
    MasonHighlightBlockBold                     { fg="#0f0f17", gui="bold", bg="#78a9ff", }, -- MasonHighlightBlockBold xxx cterm=bold gui=bold guifg=#0f0f17 guibg=#78a9ff
    MasonHighlightBlock                         { fg="#0f0f17", bg="#abe9b3", }, -- MasonHighlightBlock xxx guifg=#0f0f17 guibg=#abe9b3
    MasonHighlight                              { fg="#abe9b3", }, -- MasonHighlight xxx guifg=#abe9b3
    MasonHeaderSecondary                        { fg="#0f0f17", gui="bold", bg="#78a9ff", }, -- MasonHeaderSecondary xxx cterm=bold gui=bold guifg=#0f0f17 guibg=#78a9ff
    MasonHeader                                 { fg="#0f0f17", gui="bold", }, -- MasonHeader    xxx cterm=bold gui=bold guifg=#0f0f17
    diffAdded                                   { fg="#abe9b3", }, -- diffAdded      xxx guifg=#abe9b3
    sym"@text.diff.add"                         { diffAdded }, -- @text.diff.add xxx links to diffAdded
    diffRemoved                                 { fg="#e95678", }, -- diffRemoved    xxx guifg=#e95678
    sym"@text.diff.delete"                      { diffRemoved }, -- @text.diff.delete xxx links to diffRemoved
    diffChanged                                 { fg="#78a9ff", }, -- diffChanged    xxx guifg=#78a9ff
    diffOldFile                                 { fg="#fae3b0", }, -- diffOldFile    xxx guifg=#fae3b0
    diffNewFile                                 { fg="#ff9d64", }, -- diffNewFile    xxx guifg=#ff9d64
    diffFile                                    { fg="#78a9ff", }, -- diffFile       xxx guifg=#78a9ff
    diffIndexLine                               { fg="#b5e8e0", }, -- diffIndexLine  xxx guifg=#b5e8e0
    healthError                                 { fg="#e95678", }, -- healthError    xxx guifg=#e95678
    healthWarning                               { fg="#fae3b0", }, -- healthWarning  xxx guifg=#fae3b0
    sym"@symbol"                                { fg="#80ed99", }, -- @symbol        xxx guifg=#80ed99
    sym"@symbol.ruby"                           { fg="#f2cdcd", }, -- @symbol.ruby   xxx guifg=#f2cdcd
    sym"@field.yaml"                            { fg="#78a9ff", }, -- @field.yaml    xxx guifg=#78a9ff
    sym"@property.cpp"                          { fg="#f5e0dc", }, -- @property.cpp  xxx guifg=#f5e0dc
    sym"@tag.attribute"                         { fg="#b5e8e0", gui="italic", }, -- @tag.attribute xxx cterm=italic gui=italic guifg=#b5e8e0
    sym"@tag.attribute.tsx"                     { fg="#9d7dd8", gui="italic", }, -- @tag.attribute.tsx xxx cterm=italic gui=italic guifg=#9d7dd8
    sym"@constructor.lua"                       { fg="#f2cdcd", }, -- @constructor.lua xxx guifg=#f2cdcd
    sym"@label.json"                            { fg="#78a9ff", }, -- @label.json    xxx guifg=#78a9ff
    sym"@property.toml"                         { fg="#78a9ff", }, -- @property.toml xxx guifg=#78a9ff
    sym"@number.css"                            { fg="#ff9d64", }, -- @number.css    xxx guifg=#ff9d64
    sym"@string.plain.css"                      { fg="#ff9d64", }, -- @string.plain.css xxx guifg=#ff9d64
    sym"@type.tag.css"                          { fg="#9d7dd8", }, -- @type.tag.css  xxx guifg=#9d7dd8
    sym"@property.class.css"                    { fg="#fae3b0", }, -- @property.class.css xxx guifg=#fae3b0
    sym"@type.builtin"                          { fg="#ff7eb6", gui="italic", }, -- @type.builtin  xxx cterm=italic gui=italic guifg=#ff7eb6
    sym"@text.strike"                           { fg="#0f0f17", gui="strikethrough", }, -- @text.strike   xxx cterm=strikethrough gui=strikethrough guifg=#0f0f17
    sym"@text.emphasis"                         { fg="#f6ca6b", gui="italic", }, -- @text.emphasis xxx cterm=italic gui=italic guifg=#f6ca6b
    sym"@text.strong"                           { fg="#da4b4a", gui="bold", }, -- @text.strong   xxx cterm=bold gui=bold guifg=#da4b4a
    sym"@tag.delimiter"                         { fg="#93baff", }, -- @tag.delimiter xxx guifg=#93baff
    sym"@enum"                                  { fg="#b5e8e0", }, -- @enum          xxx guifg=#b5e8e0
    sym"@punctuation.special"                   { fg="#78a9ff", gui="bold", }, -- @punctuation.special xxx cterm=bold gui=bold guifg=#78a9ff
    sym"@text.danger"                           { fg="#0f0f17", bg="#e95678", }, -- @text.danger   xxx guifg=#0f0f17 guibg=#e95678
    sym"@punctuation.bracket"                   { fg="#93baff", }, -- @punctuation.bracket xxx guifg=#93baff
    sym"@reference"                             { fg="#cdd6f4", }, -- @reference     xxx guifg=#cdd6f4
    sym"@text.todo.checked"                     { fg="#abe9b3", }, -- @text.todo.checked xxx guifg=#abe9b3
    sym"@text.environment"                      { fg="#f5c2e7", }, -- @text.environment xxx guifg=#f5c2e7
    sym"@text.environment.name"                 { fg="#78a9ff", }, -- @text.environment.name xxx guifg=#78a9ff
    sym"@keyword.function"                      { fg="#be95ff", gui="italic", }, -- @keyword.function xxx cterm=italic gui=italic guifg=#be95ff
    sym"@attribute"                             { fg="#ff7eb6", }, -- @attribute     xxx guifg=#ff7eb6
    GlyphPalette1                               { fg="#e95678", }, -- GlyphPalette1  xxx guifg=#e95678
    RenamerBorder                               { fg="#e95678", }, -- RenamerBorder  xxx guifg=#e95678
    RenamerTitle                                { fg="#0f0f17", bg="#e95678", }, -- RenamerTitle   xxx guifg=#0f0f17 guibg=#e95678
    DiagnosticInformation                       { fg="#abe9b3", }, -- DiagnosticInformation xxx guifg=#abe9b3
    IndentBlanklineIndent2                      { fg="#555464", blend=0, }, -- IndentBlanklineIndent2 xxx guifg=#555464 blend=0
    GlyphPalette2                               { fg="#b5e8e0", }, -- GlyphPalette2  xxx guifg=#b5e8e0
    IndentBlanklineIndent1                      { fg="#363545", blend=0, }, -- IndentBlanklineIndent1 xxx guifg=#363545 blend=0
    IndentBlanklineContextStart                 { sp="#cdd6f4", gui="underline", bg="#27272e", }, -- IndentBlanklineContextStart xxx cterm=underline gui=underline guibg=#27272e guisp=#cdd6f4
    IndentBlanklineContextChar                  { fg="#be95ff", }, -- IndentBlanklineContextChar xxx guifg=#be95ff
    IndentBlanklineSpaceChar                    { fg="#363545", }, -- IndentBlanklineSpaceChar xxx guifg=#363545
    IndentBlanklineChar                         { fg="#363545", }, -- IndentBlanklineChar xxx guifg=#363545
    GlyphPalette3                               { fg="#fae3b0", }, -- GlyphPalette3  xxx guifg=#fae3b0
    VisualNOS                                   { fg="#78a9ff", gui="bold", bg="#45475a", }, -- VisualNOS      xxx cterm=bold gui=bold guifg=#78a9ff guibg=#45475a
    GlyphPalette4                               { fg="#78a9ff", }, -- GlyphPalette4  xxx guifg=#78a9ff
    TooLong                                     { fg="#78a9ff", }, -- TooLong        xxx guifg=#78a9ff
    GlyphPalette6                               { fg="#b5e8e0", }, -- GlyphPalette6  xxx guifg=#b5e8e0
    Italic                                      { gui="italic", }, -- Italic         xxx cterm=italic gui=italic
    DapStopped                                  { fg="#da4b4a", }, -- DapStopped     xxx guifg=#da4b4a
    DapUIWatchesError                           { fg="#da4b4a", }, -- DapUIWatchesError xxx guifg=#da4b4a
    IlluminatedWordText                         { bg="#353646", }, -- IlluminatedWordText xxx guibg=#353646
    Variable                                    { fg="#cdd6f4", }, -- Variable       xxx guifg=#cdd6f4
    IlluminatedWordRead                         { bg="#353646", }, -- IlluminatedWordRead xxx guibg=#353646
    IndentBlanklineIndent6                      { fg="#fae3b0", blend=0, }, -- IndentBlanklineIndent6 xxx guifg=#fae3b0 blend=0
    RainbowDelimiterCyan                        { fg="#ff7eb6", }, -- RainbowDelimiterCyan xxx guifg=#ff7eb6
    IndentBlanklineIndent4                      { fg="#b5e8e0", blend=0, }, -- IndentBlanklineIndent4 xxx guifg=#b5e8e0 blend=0
    RainbowDelimiterViolet                      { fg="#ff9e64", }, -- RainbowDelimiterViolet xxx guifg=#ff9e64
    RainbowDelimiterGreen                       { fg="#2ee6a6", }, -- RainbowDelimiterGreen xxx guifg=#2ee6a6
    RainbowDelimiterOrange                      { fg="#be95ff", }, -- RainbowDelimiterOrange xxx guifg=#be95ff
    RainbowDelimiterBlue                        { fg="#f6ca6b", }, -- RainbowDelimiterBlue xxx guifg=#f6ca6b
    NotifyWARNIcon                              { fg="#fae3b0", }, -- NotifyWARNIcon xxx guifg=#fae3b0
    RainbowDelimiterYellow                      { fg="#ee5396", }, -- RainbowDelimiterYellow xxx guifg=#ee5396
    DapUIWatchesValue                           { fg="#abe9b3", }, -- DapUIWatchesValue xxx guifg=#abe9b3
    RainbowDelimiterRed                         { fg="#25b2bc", }, -- RainbowDelimiterRed xxx guifg=#25b2bc
    DashboardShortCut                           { fg="#f5c2e7", }, -- DashboardShortCut xxx guifg=#f5c2e7
    sym"@text.warning"                          { fg="#0f0f17", bg="#fae3b0", }, -- @text.warning  xxx guifg=#0f0f17 guibg=#fae3b0
    sym"@text.note"                             { fg="#0f0f17", bg="#78a9ff", }, -- @text.note     xxx guifg=#0f0f17 guibg=#78a9ff
    sym"@text.todo.unchecked"                   { fg="#7f849c", }, -- @text.todo.unchecked xxx guifg=#7f849c
    sym"@annotation"                            { fg="#93baff", }, -- @annotation    xxx guifg=#93baff
    DashboardHeader                             { fg="#78a9ff", }, -- DashboardHeader xxx guifg=#78a9ff
    DashboardCenter                             { fg="#abe9b3", }, -- DashboardCenter xxx guifg=#abe9b3
    DashboardFooter                             { fg="#fae3b0", gui="italic", }, -- DashboardFooter xxx cterm=italic gui=italic guifg=#fae3b0
    sym"@decorator"                             { fg="#f2cdcd", }, -- @decorator     xxx guifg=#f2cdcd
    sym"@struct"                                { fg="#78a9ff", }, -- @struct        xxx guifg=#78a9ff
    LspDiagnosticsVirtualTextError              { fg="#e95678", gui="italic", }, -- LspDiagnosticsVirtualTextError xxx cterm=italic gui=italic guifg=#e95678
    LspDiagnosticsVirtualTextWarning            { fg="#fae3b0", gui="italic", }, -- LspDiagnosticsVirtualTextWarning xxx cterm=italic gui=italic guifg=#fae3b0
    sym"@event"                                 { fg="#f2cdcd", }, -- @event         xxx guifg=#f2cdcd
    sym"@interface"                             { fg="#f2cdcd", }, -- @interface     xxx guifg=#f2cdcd
    sym"@lsp.type.interface"                    { sym"@interface" }, -- @lsp.type.interface xxx links to @interface
    LspDiagnosticsUnderlineError                { sp="#e95678", gui="underline", }, -- LspDiagnosticsUnderlineError xxx cterm=underline gui=underline guisp=#e95678
    LspDiagnosticsUnderlineWarning              { sp="#fae3b0", gui="underline", }, -- LspDiagnosticsUnderlineWarning xxx cterm=underline gui=underline guisp=#fae3b0
    LspDiagnosticsUnderlineInformation          { sp="#89dceb", gui="underline", }, -- LspDiagnosticsUnderlineInformation xxx cterm=underline gui=underline guisp=#89dceb
    VimwikiHeader3                              { fg="#78a9ff", gui="bold", }, -- VimwikiHeader3 xxx cterm=bold gui=bold guifg=#78a9ff
    sym"@definition"                            { sp="#414050", gui="underline", }, -- @definition    xxx cterm=underline gui=underline guisp=#414050
    VimwikiHeader1                              { fg="#ff9d64", gui="bold", }, -- VimwikiHeader1 xxx cterm=bold gui=bold guifg=#ff9d64
    VimwikiHeader5                              { fg="#fae3b0", gui="bold", }, -- VimwikiHeader5 xxx cterm=bold gui=bold guifg=#fae3b0
    VimwikiList                                 { fg="#ff9d64", }, -- VimwikiList    xxx guifg=#ff9d64
    markdownH5                                  { fg="#f5c2e7", }, -- markdownH5     xxx guifg=#f5c2e7
    rainbowcol4                                 { fg="#78a9ff", }, -- rainbowcol4    xxx guifg=#78a9ff
    VimwikiHeaderChar                           { fg="#474656", }, -- VimwikiHeaderChar xxx guifg=#474656
    markdownLinkText                            { fg="#78a9ff", gui="underline", }, -- markdownLinkText xxx cterm=underline gui=underline guifg=#78a9ff
    TroubleCount                                { fg="#f5c2e7", bg="#45475a", }, -- TroubleCount   xxx guifg=#f5c2e7 guibg=#45475a
    VimwikiMarkers                              { fg="#a6adc8", }, -- VimwikiMarkers xxx guifg=#a6adc8
    rainbowcol2                                 { fg="#b5e8e0", }, -- rainbowcol2    xxx guifg=#b5e8e0
    markdownHeadingDelimiter                    { fg="#ff9d64", gui="bold", }, -- markdownHeadingDelimiter xxx cterm=bold gui=bold guifg=#ff9d64
    sym"@keyword.export"                        { fg="#89dceb", gui="bold", }, -- @keyword.export xxx cterm=bold gui=bold guifg=#89dceb
    sym"@property.id.css"                       { fg="#78a9ff", }, -- @property.id.css xxx guifg=#78a9ff
    sym"@typeParameter"                         { fg="#fae3b0", }, -- @typeParameter xxx guifg=#fae3b0
    sym"@regexp"                                { fg="#f5c2e7", }, -- @regexp        xxx guifg=#f5c2e7
    sym"@modifier"                              { fg="#f2cdcd", }, -- @modifier      xxx guifg=#f2cdcd
    sym"@enumMember"                            { fg="#f2cdcd", }, -- @enumMember    xxx guifg=#f2cdcd
    sym"@class"                                 { fg="#78a9ff", }, -- @class         xxx guifg=#78a9ff
    LspDiagnosticsVirtualTextInformation        { fg="#89dceb", gui="italic", }, -- LspDiagnosticsVirtualTextInformation xxx cterm=italic gui=italic guifg=#89dceb
    rainbowcol1                                 { fg="#e95678", }, -- rainbowcol1    xxx guifg=#e95678
    rainbowcol7                                 { fg="#abe9b3", }, -- rainbowcol7    xxx guifg=#abe9b3
    markdownH4                                  { fg="#fae3b0", }, -- markdownH4     xxx guifg=#fae3b0
    rainbowcol6                                 { fg="#f2cdcd", }, -- rainbowcol6    xxx guifg=#f2cdcd
    TSRainbowOrange                             { fg="#ff9d64", }, -- TSRainbowOrange xxx guifg=#ff9d64
    LspDiagnosticsVirtualTextHint               { fg="#b5e8e0", gui="italic", }, -- LspDiagnosticsVirtualTextHint xxx cterm=italic gui=italic guifg=#b5e8e0
    NotifyWARNTitle                             { fg="#fae3b0", gui="italic", }, -- NotifyWARNTitle xxx cterm=italic gui=italic guifg=#fae3b0
    TSRainbowGreen                              { fg="#abe9b3", }, -- TSRainbowGreen xxx guifg=#abe9b3
    healthSuccess                               { fg="#0f0f17", bg="#abe9b3", }, -- healthSuccess  xxx guifg=#0f0f17 guibg=#abe9b3
    LspSignatureActiveParameter                 { fg="#0f0f17", bg="#abe9b3", }, -- LspSignatureActiveParameter xxx guifg=#0f0f17 guibg=#abe9b3
    sym"@error"                                 { fg="#78a9ff", }, -- @error         xxx guifg=#78a9ff
    sym"@keyword.return"                        { fg="#be95ff", gui="italic", }, -- @keyword.return xxx cterm=italic gui=italic guifg=#be95ff
    sym"@none"                                  { fg="#cdd6f4", }, -- @none          xxx guifg=#cdd6f4
    sym"@punctuation.delimiter"                 { fg="#93baff", }, -- @punctuation.delimiter xxx guifg=#93baff
    sym"@string.regex"                          { fg="#7dcfff", }, -- @string.regex  xxx guifg=#7dcfff
    rainbowcol5                                 { fg="#f5c2e7", }, -- rainbowcol5    xxx guifg=#f5c2e7
    VimwikiHeader4                              { fg="#89dceb", gui="bold", }, -- VimwikiHeader4 xxx cterm=bold gui=bold guifg=#89dceb
    GitSignsDelete                              { fg="#e95678", }, -- GitSignsDelete xxx guifg=#e95678
    MasonMutedBlock                             { fg="#0f0f17", bg="#6c7086", }, -- MasonMutedBlock xxx guifg=#0f0f17 guibg=#6c7086
    TSRainbowBlue                               { fg="#78a9ff", }, -- TSRainbowBlue  xxx guifg=#78a9ff
    GitSignsChange                              { fg="#fae3b0", }, -- GitSignsChange xxx guifg=#fae3b0
    VimwikiHeader2                              { fg="#abe9b3", gui="bold", }, -- VimwikiHeader2 xxx cterm=bold gui=bold guifg=#abe9b3
    VimwikiHR                                   { fg="#fae3b0", }, -- VimwikiHR      xxx guifg=#fae3b0
    GitSignsAdd                                 { fg="#abe9b3", }, -- GitSignsAdd    xxx guifg=#abe9b3
    NotifyDEBUGIcon                             { fg="#ff9d64", }, -- NotifyDEBUGIcon xxx guifg=#ff9d64
    markdownCode                                { fg="#f2cdcd", }, -- markdownCode   xxx guifg=#f2cdcd
    NotifyDEBUGBorder                           { fg="#ff9d64", }, -- NotifyDEBUGBorder xxx guifg=#ff9d64
    TroubleNormal                               { fg="#cdd6f4", bg="#11111b", }, -- TroubleNormal  xxx guifg=#cdd6f4 guibg=#11111b
    NotifyERRORTitle                            { fg="#e95678", gui="italic", }, -- NotifyERRORTitle xxx cterm=italic gui=italic guifg=#e95678
    NotifyWARNBorder                            { fg="#fae3b0", }, -- NotifyWARNBorder xxx guifg=#fae3b0
    markdownH3                                  { fg="#abe9b3", }, -- markdownH3     xxx guifg=#abe9b3
    TroubleText                                 { fg="#abe9b3", }, -- TroubleText    xxx guifg=#abe9b3
    TSRainbowRed                                { fg="#e95678", }, -- TSRainbowRed   xxx guifg=#e95678
    TSRainbowYellow                             { fg="#fae3b0", }, -- TSRainbowYellow xxx guifg=#fae3b0
    TSRainbowViolet                             { fg="#9d7dd8", }, -- TSRainbowViolet xxx guifg=#9d7dd8
    sym"@text.math"                             { fg="#78a9ff", }, -- @text.math     xxx guifg=#78a9ff
    TSRainbowCyan                               { fg="#b5e8e0", }, -- TSRainbowCyan  xxx guifg=#b5e8e0
    rainbowcol3                                 { fg="#fae3b0", }, -- rainbowcol3    xxx guifg=#fae3b0
    IndentBlanklineIndent3                      { fg="#ff9d64", blend=0, }, -- IndentBlanklineIndent3 xxx guifg=#ff9d64 blend=0
    DapUIStoppedThread                          { fg="#89dceb", }, -- DapUIStoppedThread xxx guifg=#89dceb
    TSDefinitionUsage                           { sp="#414050", gui="underline", }, -- TSDefinitionUsage xxx cterm=underline gui=underline guisp=#414050
    DapUIBreakpointsInfo                        { fg="#abe9b3", }, -- DapUIBreakpointsInfo xxx guifg=#abe9b3
    -- WhichKey                                    { }, -- WhichKey       xxx cterm= gui=
    -- WhichKeyFloat                               { }, -- WhichKeyFloat  xxx cterm= gui=
    -- WhichKeyValue                               { }, -- WhichKeyValue  xxx cterm= gui=
    -- WhichKeyDesc                                { }, -- WhichKeyDesc   xxx cterm= gui=
    -- WhichKeyGroup                               { }, -- WhichKeyGroup  xxx cterm= gui=
    -- WhichKeySeparator                           { }, -- WhichKeySeparator xxx cterm= gui=
    -- WhichKeyBorder                              { }, -- WhichKeyBorder xxx cterm= gui=
    -- GitSignsChangedelete                        { }, -- GitSignsChangedelete xxx cterm= gui=
    -- GitSignsTopdelete                           { }, -- GitSignsTopdelete xxx cterm= gui=
    -- GitSignsUntracked                           { }, -- GitSignsUntracked xxx cterm= gui=
    -- GitSignsAddNr                               { }, -- GitSignsAddNr  xxx cterm= gui=
    -- GitSignsChangeNr                            { }, -- GitSignsChangeNr xxx cterm= gui=
    -- GitSignsDeleteNr                            { }, -- GitSignsDeleteNr xxx cterm= gui=
    -- GitSignsChangedeleteNr                      { }, -- GitSignsChangedeleteNr xxx cterm= gui=
    -- GitSignsTopdeleteNr                         { }, -- GitSignsTopdeleteNr xxx cterm= gui=
    -- GitSignsUntrackedNr                         { }, -- GitSignsUntrackedNr xxx cterm= gui=
    -- GitSignsAddLn                               { }, -- GitSignsAddLn  xxx cterm= gui=
    -- GitSignsChangeLn                            { }, -- GitSignsChangeLn xxx cterm= gui=
    -- GitSignsChangedeleteLn                      { }, -- GitSignsChangedeleteLn xxx cterm= gui=
    -- GitSignsUntrackedLn                         { }, -- GitSignsUntrackedLn xxx cterm= gui=
    GitSignsStagedAdd                           { fg="#557459", }, -- GitSignsStagedAdd xxx cterm= gui= guifg=#557459
    GitSignsStagedChange                        { fg="#7d7158", }, -- GitSignsStagedChange xxx cterm= gui= guifg=#7d7158
    GitSignsStagedDelete                        { fg="#742b3c", }, -- GitSignsStagedDelete xxx cterm= gui= guifg=#742b3c
    GitSignsStagedChangedelete                  { fg="#7d7158", }, -- GitSignsStagedChangedelete xxx cterm= gui= guifg=#7d7158
    GitSignsStagedTopdelete                     { fg="#742b3c", }, -- GitSignsStagedTopdelete xxx cterm= gui= guifg=#742b3c
    GitSignsStagedAddNr                         { fg="#557459", }, -- GitSignsStagedAddNr xxx cterm= gui= guifg=#557459
    GitSignsStagedChangeNr                      { fg="#7d7158", }, -- GitSignsStagedChangeNr xxx cterm= gui= guifg=#7d7158
    GitSignsStagedDeleteNr                      { fg="#742b3c", }, -- GitSignsStagedDeleteNr xxx cterm= gui= guifg=#742b3c
    GitSignsStagedChangedeleteNr                { fg="#7d7158", }, -- GitSignsStagedChangedeleteNr xxx cterm= gui= guifg=#7d7158
    GitSignsStagedTopdeleteNr                   { fg="#742b3c", }, -- GitSignsStagedTopdeleteNr xxx cterm= gui= guifg=#742b3c
    GitSignsStagedAddLn                         { bg="#2b3633", }, -- GitSignsStagedAddLn xxx cterm= gui= guibg=#2b3633
    GitSignsStagedChangeLn                      { bg="#161a27", }, -- GitSignsStagedChangeLn xxx cterm= gui= guibg=#161a27
    GitSignsStagedChangedeleteLn                { bg="#161a27", }, -- GitSignsStagedChangedeleteLn xxx cterm= gui= guibg=#161a27
    -- GitSignsCurrentLineBlame                    { }, -- GitSignsCurrentLineBlame xxx cterm= gui=
    -- GitSignsAddInline                           { }, -- GitSignsAddInline xxx cterm= gui=
    -- GitSignsDeleteInline                        { }, -- GitSignsDeleteInline xxx cterm= gui=
    -- GitSignsChangeInline                        { }, -- GitSignsChangeInline xxx cterm= gui=
    -- GitSignsAddLnInline                         { }, -- GitSignsAddLnInline xxx cterm= gui=
    -- GitSignsChangeLnInline                      { }, -- GitSignsChangeLnInline xxx cterm= gui=
    -- GitSignsDeleteLnInline                      { }, -- GitSignsDeleteLnInline xxx cterm= gui=
    -- GitSignsDeleteVirtLn                        { }, -- GitSignsDeleteVirtLn xxx cterm= gui=
    -- GitSignsDeleteVirtLnInLine                  { }, -- GitSignsDeleteVirtLnInLine xxx cterm= gui=
    -- GitSignsVirtLnum                            { }, -- GitSignsVirtLnum xxx cterm= gui=
  }
end)
return theme
